import React from "react";
import styles from "./DobieFrame.module.css";
export default function DobieFrame() {
  // 컴포넌트 로직
  return (
    <div id="dobie">
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
    </div>
  );
}
