import React, { forwardRef } from "react";
import styles from "./OverviewFrame.module.css";
export default function OverviewFrame() {
  // 컴포넌트 로직
  return (
    <div id="overview">
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div id="overview1">gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div id="regist">gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
      <div>gdddddddddddddd</div>
    </div>
  );
}
